"""Exness connector — forex/CFD trading on the owner's Exness account.

Endpoint + signing map MINED 2026-10-09 (not guessed):

* Official docs: https://www.exness-api.com/documentation/create-api-key —
  API keys are created in the Personal Area's Key Management (never through
  the API); the client stores ``EXN_API_KEY`` (public key id),
  ``EXN_PRIVATE_KEY`` (the secret, shown once), ``EXN_ACCOUNT_ID`` (the
  trading account the key may touch), and ``EXN_API_BASE_URL`` (the host
  from the DNS widget; ``https://api.exness.com`` is the main host).
* Path + signing semantics verified against the working third-party SDK
  ``realm-dev/exnesssdk`` (``src/auth/signer.ts``, ``src/api/*.ts``):
  every request is signed with Ed25519 over the UTF-8 bytes of a JSON
  payload ``{"api_key", "idempotency_key", "timestamp", "sign_version": 1,
  "method", "path" (path+query exactly as transmitted), "body_hash"}``;
  the signature and the base64url payload ride in the ``EXN-SIGN`` /
  ``EXN-DATA`` headers alongside ``EXN-API-KEY``, ``EXN-TIMESTAMP``,
  ``EXN-SIGN-VERSION``, ``EXN-IDEMPOTENCY-KEY``. The server tolerates
  ``0 <= server_now_ms - timestamp_ms <= 3000`` (asymmetric — a client
  clock even slightly ahead is rejected), so this client biases its clock
  1s into the past and learns the offset from HTTP ``Date`` headers.
* Trading calls run against the per-account access point discovered via
  ``GET /v1/trading/access-point?account_id=...``; configuration and
  market-data calls run against the main host.

The Ed25519 below is a native RFC 8032 implementation (extended twisted-
Edwards coordinates — one modular inverse per signature, ~7ms). It is
verified in the test-suite against a signature generated by an
independent implementation (``cryptography``), not against itself.

Money safety (mirrors the Duffel architecture):

* ``open_position`` / ``close_position`` / ``close_all_positions`` /
  ``place_pending_order`` / ``modify_order`` / ``cancel_order(s)`` move
  real money and refuse to run without explicit owner confirmation
  (``confirmed=True`` after the owner approved the exact payload, or a
  human checkpoint when ``db`` is given). No silent success.
* Demo-first: connect with a demo trading account id while testing.

Auth: ``AuthMethod.API_KEY``. Env vars: ``EXNESS_API_KEY``,
``EXNESS_PRIVATE_KEY`` (the 32-byte seed as base64url, base64, or hex),
``EXNESS_ACCOUNT_ID``, ``EXNESS_API_BASE_URL`` (optional).
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import time
import urllib.parse
import uuid
from email.utils import parsedate_to_datetime
from typing import Any

from ..core.errors import NoMoralsError, RateLimited
from ..core.logging_setup import get_logger
from .auth import prompt_secret
from .base import (
    AuthMethod,
    Connector,
    ConnectorError,
    ConnectorStatus,
    ConnectResult,
)
from ._confirm import confirm_or_checkpoint
from .registry import register_connector

__all__ = ["ExnessConnector", "ExnessError"]

_log = get_logger(__name__)

API_BASE = "https://api.exness.com"
KEY_ENV = "EXNESS_API_KEY"
PRIVATE_KEY_ENV = "EXNESS_PRIVATE_KEY"
ACCOUNT_ID_ENV = "EXNESS_ACCOUNT_ID"
BASE_URL_ENV = "EXNESS_API_BASE_URL"
DOCS_URL = "https://www.exness-api.com/documentation/create-api-key"

#: Server timestamp tolerance is asymmetric: bias our clock into the past.
_CLOCK_SAFETY_MARGIN_MS = 1000
_CLOCK_TOLERANCE_MS = 3000


class ExnessError(ConnectorError):
    """An Exness API call failed."""

    def __init__(
        self,
        message: str,
        *,
        error_code: int = 0,
        status_code: int = 0,
    ) -> None:
        super().__init__(message)
        self.error_code = error_code
        self.status_code = status_code


# ── native RFC 8032 Ed25519 (extended coordinates) ─────────────────────────
#
# Pure stdlib (hashlib only): no third-party crypto dependency, so this
# works on Termux and locked-down profiles. Verified in
# tests/test_exness_connector.py against a signature + public key generated
# by the independent ``cryptography`` implementation.

_ED_Q = (1 << 255) - 19
_ED_L = (1 << 252) + 27742317777372353535851937790883648493
_ED_D = (-121665 * pow(121666, _ED_Q - 2, _ED_Q)) % _ED_Q
_ED_D2 = (2 * _ED_D) % _ED_Q


def _ed_h(data: bytes) -> bytes:
    return hashlib.sha512(data).digest()


def _ed_xrecover(y: int) -> int:
    xx = (y * y - 1) * pow(_ED_D * y * y + 1, _ED_Q - 2, _ED_Q) % _ED_Q
    x = pow(xx, (_ED_Q + 3) // 8, _ED_Q)
    if (x * x - xx) % _ED_Q != 0:
        x = (x * pow(2, (_ED_Q - 1) // 4, _ED_Q)) % _ED_Q
    return _ED_Q - x if x & 1 else x


_ED_BY = (4 * pow(5, _ED_Q - 2, _ED_Q)) % _ED_Q
_ED_BX = _ed_xrecover(_ED_BY)
#: Base point in extended coordinates (X, Y, Z, T); x = X/Z, y = Y/Z.
_ED_B = (_ED_BX, _ED_BY, 1, (_ED_BX * _ED_BY) % _ED_Q)
_ED_IDENT = (0, 1, 1, 0)


def _ed_add(
    p: tuple[int, int, int, int], q: tuple[int, int, int, int]
) -> tuple[int, int, int, int]:
    X1, Y1, Z1, T1 = p
    X2, Y2, Z2, T2 = q
    A = (Y1 - X1) * (Y2 - X2) % _ED_Q
    B = (Y1 + X1) * (Y2 + X2) % _ED_Q
    C = T1 * _ED_D2 % _ED_Q * T2 % _ED_Q
    Dd = 2 * Z1 * Z2 % _ED_Q
    E = (B - A) % _ED_Q
    F = (Dd - C) % _ED_Q
    G = (Dd + C) % _ED_Q
    H = (B + A) % _ED_Q
    return (E * F % _ED_Q, G * H % _ED_Q, F * G % _ED_Q, E * H % _ED_Q)


def _ed_double(p: tuple[int, int, int, int]) -> tuple[int, int, int, int]:
    X1, Y1, Z1, _T1 = p
    A = X1 * X1 % _ED_Q
    B = Y1 * Y1 % _ED_Q
    C = 2 * Z1 * Z1 % _ED_Q
    D = (-A) % _ED_Q  # curve parameter a = -1
    E = ((X1 + Y1) * (X1 + Y1) - A - B) % _ED_Q
    G = (D + B) % _ED_Q
    F = (G - C) % _ED_Q
    H = (D - B) % _ED_Q
    return (E * F % _ED_Q, G * H % _ED_Q, F * G % _ED_Q, E * H % _ED_Q)


def _ed_scalarmult_base(e: int) -> tuple[int, int]:
    """``e * B`` in affine coordinates (one inverse, at the very end)."""
    q = _ED_IDENT
    for i in range(e.bit_length() - 1, -1, -1):
        q = _ed_double(q)
        if (e >> i) & 1:
            q = _ed_add(q, _ED_B)
    X, Y, Z, _T = q
    zinv = pow(Z, _ED_Q - 2, _ED_Q)
    return (X * zinv % _ED_Q, Y * zinv % _ED_Q)


def _ed_encode_point(x: int, y: int) -> bytes:
    return ((y & ((1 << 255) - 1)) | ((x & 1) << 255)).to_bytes(32, "little")


def _ed_clamp(h32: bytes) -> int:
    a = int.from_bytes(h32, "little")
    a &= ~(1 | 2 | 4)  # clear lowest three bits
    a &= ~(1 << 255)  # clear highest bit
    a |= 1 << 254  # set second-highest bit
    return a


def ed25519_publickey(seed: bytes) -> bytes:
    """The 32-byte public key for a 32-byte seed."""
    if len(seed) != 32:
        raise ValueError("ed25519 seed must be exactly 32 bytes")
    x, y = _ed_scalarmult_base(_ed_clamp(_ed_h(seed)[:32]))
    return _ed_encode_point(x, y)


def ed25519_sign(seed: bytes, msg: bytes) -> bytes:
    """Deterministic RFC 8032 signature of ``msg`` under ``seed``."""
    if len(seed) != 32:
        raise ValueError("ed25519 seed must be exactly 32 bytes")
    h = _ed_h(seed)
    a = _ed_clamp(h[:32])
    r = int.from_bytes(_ed_h(h[32:64] + msg), "little")
    rx, ry = _ed_scalarmult_base(r)
    big_r = _ed_encode_point(rx, ry)
    k = int.from_bytes(_ed_h(big_r + ed25519_publickey(seed) + msg), "little")
    s = (r + k * a) % _ED_L
    return big_r + s.to_bytes(32, "little")


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _parse_private_seed(raw: str) -> bytes:
    """The Key Management secret → 32-byte Ed25519 seed.

    Accepts base64url (no padding), standard base64, or 64-char hex —
    Key Management shows the secret once and its encoding is easy to
    mangle in transit, so all three are tried before failing.
    """
    text = (raw or "").strip().strip("\"'")
    if not text:
        raise ExnessError("empty Exness private key: nothing to sign with")
    candidates: list[bytes] = []
    if all(c in "0123456789abcdefABCDEF" for c in text) and len(text) == 64:
        candidates.append(bytes.fromhex(text))
    padded = text + "=" * (-len(text) % 4)
    for decoder in (base64.urlsafe_b64decode, base64.b64decode):
        try:
            candidates.append(decoder(padded))
        except Exception:  # noqa: BLE001 - try the next encoding
            continue
    for blob in candidates:
        if len(blob) == 32:
            return blob
    raise ExnessError(
        "Exness private key did not decode to 32 bytes "
        f"(got {[len(b) for b in candidates] or 'nothing decodable'}) — "
        "copy the secret from Key Management again (base64url, base64, or "
        "hex are accepted)"
    )


@register_connector
class ExnessConnector(Connector):
    """Trade forex/CFDs on the owner's Exness account via the Public Trader API."""

    id = "exness"
    name = "Exness"
    description = (
        "Exness forex/CFD trading: account state, instruments, candles, "
        "market + pending orders with explicit confirmation"
    )
    auth_methods = (AuthMethod.API_KEY,)

    def __init__(self, vault: Any, http: Any = None) -> None:
        super().__init__(vault, http=http)
        self._trading_host: str | None = None
        self._clock_offset_ms: int = 0

    # ── credential plumbing ──────────────────────────────────────────

    def _auth(self) -> tuple[str, str, bytes, str]:
        """(account_id, api_key, seed, base_url) from the vault."""
        cred = self._load_credential()
        if cred is None:
            raise ExnessError(
                "Exness is not connected — run "
                "`nm connectors connect --name exness` "
                "(needs EXNESS_API_KEY, EXNESS_PRIVATE_KEY, "
                "EXNESS_ACCOUNT_ID from Key Management in your Personal Area)"
            )
        try:
            blob = json.loads(cred.password)
            seed = _parse_private_seed(blob["private_key"])
            return (
                cred.username,
                blob["api_key"],
                seed,
                blob.get("base_url") or API_BASE,
            )
        except (KeyError, ValueError, TypeError) as exc:
            raise ExnessError(
                f"stored Exness credential is corrupt ({exc}) — disconnect "
                "and reconnect"
            ) from exc

    # ── signing ──────────────────────────────────────────────────────

    def _signed_headers(
        self,
        api_key: str,
        seed: bytes,
        method: str,
        path_qs: str,
        body: bytes,
        idempotency_key: str,
    ) -> dict[str, str]:
        timestamp = (
            int(time.time() * 1000) + self._clock_offset_ms
            - _CLOCK_SAFETY_MARGIN_MS
        )
        body_hash = _b64url(hashlib.sha256(body).digest())
        payload = {
            "api_key": api_key,
            "idempotency_key": idempotency_key,
            "timestamp": timestamp,
            "sign_version": 1,
            "method": method.upper(),
            "path": path_qs,
            "body_hash": body_hash,
        }
        payload_bytes = json.dumps(
            payload, separators=(",", ":"), ensure_ascii=True
        ).encode("utf-8")
        return {
            "EXN-API-KEY": api_key,
            "EXN-TIMESTAMP": str(timestamp),
            "EXN-SIGN-VERSION": "1",
            "EXN-IDEMPOTENCY-KEY": idempotency_key,
            "EXN-DATA": _b64url(payload_bytes),
            "EXN-SIGN": _b64url(ed25519_sign(seed, payload_bytes)),
            "Content-Type": "application/json",
        }

    def _learn_clock_offset(self, resp: Any) -> None:
        """Sync our clock bias from the server's Date header (SDK §signed auth)."""
        try:
            date = (resp.headers or {}).get("date")
            if not date:
                return
            server_ms = int(parsedate_to_datetime(date).timestamp() * 1000)
            now_ms = int(time.time() * 1000)
            # Bias slightly into the past: the tolerance is asymmetric and a
            # client clock even slightly ahead is rejected.
            self._clock_offset_ms = server_ms - now_ms - _CLOCK_SAFETY_MARGIN_MS
        except Exception:  # noqa: BLE001 - clock sync is best-effort
            pass

    # ── REST ─────────────────────────────────────────────────────────

    def _api(
        self,
        method: str,
        path: str,
        *,
        host_kind: str = "config",
        params: dict[str, Any] | None = None,
        json_body: dict[str, Any] | None = None,
        idempotency_key: str | None = None,
        account_id: str | None = None,
        api_key: str | None = None,
        seed: bytes | None = None,
        base_url: str | None = None,
    ) -> Any:
        if account_id is None or api_key is None or seed is None:
            # Normal path: credentials come from the vault. The connect()
            # validation call passes all three explicitly because nothing
            # is vaulted yet.
            stored_id, stored_key, stored_seed, stored_base = self._auth()
            account_id = account_id or stored_id
            api_key = api_key or stored_key
            seed = seed or stored_seed
            base_url = base_url or stored_base
        base_url = base_url or API_BASE
        if host_kind == "trading":
            base_url = self._trading_host or self._resolve_trading_host(
                account_id, api_key, seed, base_url
            )
        clean = {k: v for k, v in (params or {}).items() if v is not None}
        path_qs = path + (
            "?" + urllib.parse.urlencode(clean, doseq=True) if clean else ""
        )
        body = (
            json.dumps(json_body, separators=(",", ":"),
                       ensure_ascii=True).encode("utf-8")
            if json_body is not None
            else b""
        )
        if idempotency_key is None:
            idempotency_key = uuid.uuid4().hex if body or method != "GET" else ""
        headers = self._signed_headers(
            api_key, seed, method, path_qs, body, idempotency_key
        )
        try:
            resp = self.http.request(
                method.upper(),
                f"{base_url.rstrip('/')}{path_qs}",
                data=body or None,
                headers=headers,
            )
        except RateLimited as exc:
            raise ExnessError(
                f"Exness rate limited (429) — back off ~{exc.retry_after:.0f}s",
                error_code=1,
                status_code=429,
            ) from exc
        except NoMoralsError as exc:
            raise ExnessError(f"Exness request failed: {exc}") from exc
        except Exception as exc:  # noqa: BLE001 - network layer is opaque
            raise ExnessError(f"Exness request failed: {exc}") from exc
        self._learn_clock_offset(resp)
        try:
            data = resp.json()
        except Exception as exc:  # noqa: BLE001 - invalid JSON is an error
            raise ExnessError(
                f"Exness {method} {path} returned invalid JSON"
            ) from exc
        if isinstance(data, dict) and "error_message" in data:
            code = int(data.get("code") or 0)
            raise ExnessError(
                f"Exness error {code}: {data.get('error_message')}",
                error_code=code,
            )
        return data

    def _resolve_trading_host(
        self, account_id: str, api_key: str, seed: bytes, base_url: str
    ) -> str:
        """Per-account trading access point (cached for the session)."""
        data = self._api(
            "GET",
            "/v1/trading/access-point",
            params={"account_id": account_id},
            api_key=api_key,
            seed=seed,
            base_url=base_url,
        )
        host = str(data.get("access_point") or "").rstrip("/")
        if not host.startswith("http"):
            raise ExnessError(
                f"access-point discovery returned {host!r} — cannot route "
                "trading calls"
            )
        self._trading_host = host
        _log.info("exness: trading access point %s", host)
        return host

    # ── lifecycle ────────────────────────────────────────────────────

    def connect(
        self,
        *,
        api_key: str | None = None,
        private_key: str | None = None,
        account_id: str | None = None,
        base_url: str | None = None,
    ) -> ConnectResult:
        """Validate Exness API credentials and vault them.

        Create the key in your Personal Area → Key Management (select the
        trading account the key may touch), then supply the public key id,
        the one-time secret, and the account id. The secret is parsed as a
        32-byte Ed25519 seed (base64url, base64, or hex).
        """
        existing = self._load_credential()
        if existing is not None:
            raise ConnectorError(
                "exness is already connected — one account per service. "
                "Disconnect first to switch accounts."
            )
        key = ((api_key or "").strip() or prompt_secret(
            "Exness API key (Key Management → public key)", env_var=KEY_ENV
        ))
        secret = ((private_key or "").strip() or prompt_secret(
            "Exness private key (the one-time secret)", env_var=PRIVATE_KEY_ENV
        ))
        acct = ((account_id or "").strip() or prompt_secret(
            "Exness trading account id", env_var=ACCOUNT_ID_ENV
        ))
        if not key or not secret or not acct:
            raise ConnectorError(
                "empty API key / private key / account id: nothing to "
                "connect with"
            )
        seed = _parse_private_seed(secret)
        host = (base_url or "").strip() or (
            os.environ.get(BASE_URL_ENV, "").strip() or API_BASE
        )
        details = self._api(
            "GET",
            f"/v1/configuration/accounts/{acct}/account",
            account_id=acct,
            api_key=key,
            seed=seed,
            base_url=host,
        )
        settings = details.get("settings") or {}
        currency = settings.get("currency", "?")
        self._store_credential(
            acct,
            json.dumps(
                {"api_key": key, "private_key": secret, "base_url": host}
            ),
            credential_type="api_key",
            scopes=["trade:read", "trade:write", "market-data:read"],
            metadata={"docs": DOCS_URL},
        )
        _log.info("exness connected (account %s)", acct)
        return ConnectResult(
            ok=True,
            account=f"exness:{acct}",
            scopes=["trade:read", "trade:write", "market-data:read"],
            message=(
                f"connected to Exness (account {acct}, {currency}). The API "
                "key + private seed are in the encrypted vault. Every order "
                "still needs your explicit confirmation at call time — "
                "connect a DEMO account id while testing."
            ),
        )

    def disconnect(self) -> None:
        self._clear_credential()
        self._trading_host = None

    def status(self) -> ConnectorStatus:
        account_id, _key, _seed, _base = self._auth_or_none()
        if account_id is None:
            return ConnectorStatus(
                connected=False,
                detail="not connected — run `nm connectors connect "
                       "--name exness` (keys come from Key Management in "
                       "your Exness Personal Area)",
            )
        try:
            snap = self._api(
                "GET", f"/v1/trading/accounts/{account_id}/snapshot",
                host_kind="trading",
            )
        except ExnessError as exc:
            return ConnectorStatus(
                connected=False,
                account=f"exness:{account_id}",
                last_checked=time.time(),
                detail=f"API rejected the key ({exc}): rotate it in Key "
                       "Management and reconnect",
            )
        state = snap.get("account_state") or {}
        n_pos = len(snap.get("positions") or [])
        n_ord = len(snap.get("orders") or [])
        return ConnectorStatus(
            connected=True,
            account=f"exness:{account_id}",
            scopes=["trade:read", "trade:write", "market-data:read"],
            last_checked=time.time(),
            detail=(
                f"balance={state.get('balance', '?')} "
                f"equity={state.get('equity', '?')} "
                f"margin={state.get('used_margin', '?')} "
                f"positions={n_pos} orders={n_ord}"
            ),
        )

    def _auth_or_none(self) -> tuple[str | None, str, bytes, str]:
        try:
            return self._auth()
        except ExnessError:
            return (None, "", b"", "")

    def test_connection(self) -> bool:
        try:
            return self.status().connected
        except Exception:  # noqa: BLE001 - offline / bad key → not linked
            return False

    # ── configuration / market data (read-only) ──────────────────────

    def get_account_details(self) -> dict[str, Any]:
        """Account settings: currency, leverage, trade mode, status."""
        account_id, *_ = self._auth()
        return self._api(
            "GET", f"/v1/configuration/accounts/{account_id}/account"
        )

    def get_snapshot(self) -> dict[str, Any]:
        """Live account state + open positions + pending orders."""
        account_id, *_ = self._auth()
        return self._api(
            "GET", f"/v1/trading/accounts/{account_id}/snapshot",
            host_kind="trading",
        )

    def get_instruments(self) -> list[str]:
        """Tradeable instrument names for this account."""
        account_id, *_ = self._auth()
        data = self._api(
            "GET", f"/v1/configuration/accounts/{account_id}/instruments"
        )
        return list(data.get("instruments") or [])

    def get_instrument_condition(self, instrument: str) -> dict[str, Any]:
        """Contract terms: digits, volume min/max/step, margins, swaps."""
        account_id, *_ = self._auth()
        instrument = (instrument or "").strip().upper()
        if not instrument:
            raise ExnessError("empty instrument")
        return self._api(
            "GET",
            f"/v1/configuration/accounts/{account_id}/instruments/"
            f"{instrument}/conditions",
        )

    def get_limits(self) -> dict[str, Any]:
        """REST + websocket rate limits for this account."""
        account_id, *_ = self._auth()
        return self._api(
            "GET", f"/v1/configuration/accounts/{account_id}/limits"
        )

    def get_candles(
        self,
        instrument: str,
        timeframe: str,
        *,
        from_time: str = "",
        to_time: str = "",
        count: int = 100,
        price_type: str = "bid",
    ) -> list[dict[str, Any]]:
        """OHLC history. ``timeframe`` like ``M15``/``H1``/``H4``/``D1``;
        ``from_time``/``to_time`` are ISO datetimes; ``count`` ±1..1000."""
        account_id, *_ = self._auth()
        instrument = (instrument or "").strip().upper()
        if not instrument:
            raise ExnessError("empty instrument")
        data = self._api(
            "GET",
            f"/v1/market-data/accounts/{account_id}/candles",
            params={
                "instrument": instrument,
                "timeframe": (timeframe or "").strip().upper() or "H1",
                "from": from_time or None,
                "to": to_time or None,
                "count": max(-1000, min(1000, count)) or 100,
                "price_type": price_type,
            },
        )
        return list(data.get("candles") or [])

    def get_operation_status(self, operation_id: str) -> dict[str, Any]:
        """Poll an async trading operation (open/close ack → final state)."""
        account_id, *_ = self._auth()
        operation_id = (operation_id or "").strip()
        if not operation_id:
            raise ExnessError("empty operation_id")
        return self._api(
            "GET",
            f"/v1/trading/accounts/{account_id}/operations/{operation_id}",
            host_kind="trading",
        )

    def orders_history(
        self, *, limit: int = 50, **filters: Any
    ) -> dict[str, Any]:
        """Historical orders (filters: from, to, instrument, side, state)."""
        account_id, *_ = self._auth()
        return self._api(
            "GET",
            f"/v1/history/accounts/{account_id}/orders",
            params={"limit": max(1, min(1000, limit)), **filters},
        )

    def deals_history(self, *, limit: int = 50, **filters: Any) -> dict[str, Any]:
        """Historical deals (filters: from, to, instrument, side)."""
        account_id, *_ = self._auth()
        return self._api(
            "GET",
            f"/v1/history/accounts/{account_id}/deals",
            params={"limit": max(1, min(1000, limit)), **filters},
        )

    # ── money-moving calls (confirmation-gated) ──────────────────────

    def _format_prices(
        self, instrument: str, **prices: float | None
    ) -> dict[str, str]:
        """Round SL/TP/price to the instrument's point digits (the server
        rejects raw floats with REQUEST_INVALID_PRICE)."""
        digits = 2
        try:
            cond = self.get_instrument_condition(instrument)
            digits = int(cond.get("point_digits") or 2)
        except ExnessError:
            pass  # fall back to 2dp rather than refusing the trade
        out: dict[str, str] = {}
        for name, value in prices.items():
            if value is not None:
                out[name] = f"{float(value):.{digits}f}"
        return out

    def _gate(
        self,
        *,
        confirmed: bool,
        db: Any,
        context: Any,
        stage: str,
        title: str,
        instructions: str,
        resume_state: dict[str, Any],
    ) -> None:
        confirm_or_checkpoint(
            self,
            confirmed=confirmed,
            db=db,
            context=context,
            stage=stage,
            title=title,
            instructions=instructions,
            resume_state=resume_state,
        )

    def open_position(
        self,
        instrument: str,
        side: str,
        volume: float,
        *,
        price: float | None = None,
        deviation: float | None = None,
        stop_loss: float | None = None,
        take_profit: float | None = None,
        comment: str = "",
        idempotency_key: str | None = None,
        confirmed: bool = False,
        db: Any = None,
        context: Any = None,
    ) -> dict[str, Any]:
        """Open a market position. Moves real money — confirmation-gated."""
        account_id, *_ = self._auth()
        instrument = (instrument or "").strip().upper()
        side = (side or "").strip().lower()
        if not instrument:
            raise ExnessError("empty instrument")
        if side not in ("buy", "sell"):
            raise ExnessError(f"side must be 'buy' or 'sell', got {side!r}")
        if not volume or volume <= 0:
            raise ExnessError(f"volume must be positive, got {volume!r}")
        priced = self._format_prices(
            instrument, price=price, stop_loss_price=stop_loss,
            take_profit_price=take_profit,
        )
        body: dict[str, Any] = {
            "instrument": instrument,
            "side": side,
            "volume": str(volume),
            **priced,
            **({"deviation": str(deviation)} if deviation else {}),
            **({"comment": comment[:128]} if comment else {}),
        }
        self._gate(
            confirmed=confirmed, db=db, context=context, stage="open_position",
            title=f"Exness: {side} {volume} {instrument}",
            instructions="\n".join([
                "Devon wants to open a live position on Exness.",
                "This moves REAL money on your Exness account.",
                f"account={account_id} instrument={instrument} side={side} "
                f"volume={volume}",
                f"SL={priced.get('stop_loss_price', '—')} "
                f"TP={priced.get('take_profit_price', '—')}",
                "Approve ONLY if the instrument, side, volume, SL and TP "
                "above are exactly what you want.",
            ]),
            resume_state={"op": "open_position", "body": body,
                          "idempotency_key": idempotency_key or uuid.uuid4().hex},
        )
        return self._api(
            "POST",
            f"/v1/trading/accounts/{account_id}/positions",
            host_kind="trading",
            json_body=body,
            idempotency_key=idempotency_key,
        )

    def close_position(
        self,
        position_id: str,
        *,
        volume: float | None = None,
        price: float | None = None,
        confirmed: bool = False,
        db: Any = None,
        context: Any = None,
    ) -> dict[str, Any]:
        """Close (or partially close) a position. Confirmation-gated."""
        account_id, *_ = self._auth()
        position_id = (position_id or "").strip()
        if not position_id:
            raise ExnessError("empty position_id")
        params = {
            "volume": str(volume) if volume else None,
            "price": str(price) if price else None,
        }
        self._gate(
            confirmed=confirmed, db=db, context=context,
            stage="close_position",
            title=f"Exness: close position {position_id}",
            instructions="\n".join([
                "Devon wants to close a live position on Exness.",
                f"account={account_id} position={position_id} "
                f"volume={'all' if not volume else volume}",
                "Approve ONLY if this is the position you want closed.",
            ]),
            resume_state={"op": "close_position",
                          "position_id": position_id, "params": params},
        )
        return self._api(
            "DELETE",
            f"/v1/trading/accounts/{account_id}/positions/{position_id}",
            host_kind="trading",
            params=params,
        )

    def close_all_positions(
        self,
        *,
        instrument: str = "",
        side: str = "",
        profitable: bool | None = None,
        confirmed: bool = False,
        db: Any = None,
        context: Any = None,
    ) -> dict[str, Any]:
        """Close every position matching the filters. Confirmation-gated."""
        account_id, *_ = self._auth()
        params = {
            "filter": "all",
            "instrument": instrument.strip().upper() or None,
            "side": side.strip().lower() or None,
            "profitable": profitable,
            "unprofitable": (not profitable)
            if profitable is not None else None,
        }
        self._gate(
            confirmed=confirmed, db=db, context=context,
            stage="close_all_positions",
            title="Exness: CLOSE ALL positions"
            + (f" on {instrument}" if instrument else ""),
            instructions="\n".join([
                "Devon wants to CLOSE positions on Exness — this can close "
                "MANY positions at once.",
                f"account={account_id} filters={params}",
                "Approve ONLY if you really want these closed.",
            ]),
            resume_state={"op": "close_all_positions", "params": params},
        )
        return self._api(
            "DELETE",
            f"/v1/trading/accounts/{account_id}/positions",
            host_kind="trading",
            params=params,
        )

    def place_pending_order(
        self,
        order_type: str,
        instrument: str = "",
        side: str = "",
        volume: float = 0,
        *,
        price: float | None = None,
        stop_loss: float | None = None,
        take_profit: float | None = None,
        position_id: str = "",
        comment: str = "",
        idempotency_key: str | None = None,
        confirmed: bool = False,
        db: Any = None,
        context: Any = None,
    ) -> dict[str, Any]:
        """Place a limit / stop / sltp pending order. Confirmation-gated."""
        account_id, *_ = self._auth()
        order_type = (order_type or "").strip().lower()
        if order_type not in ("limit", "stop", "sltp"):
            raise ExnessError(
                f"order_type must be limit|stop|sltp, got {order_type!r}"
            )
        if order_type == "sltp":
            body: dict[str, Any] = {
                "type": "sltp",
                "position_id": (position_id or "").strip(),
            }
            if not body["position_id"]:
                raise ExnessError("sltp orders need position_id")
        else:
            instrument = (instrument or "").strip().upper()
            side = (side or "").strip().lower()
            if not instrument or side not in ("buy", "sell") or not volume:
                raise ExnessError(
                    "limit/stop orders need instrument, side (buy|sell), "
                    "volume, and price"
                )
            if price is None:
                raise ExnessError("limit/stop orders need price")
            priced = self._format_prices(
                instrument, price=price, stop_loss_price=stop_loss,
                take_profit_price=take_profit,
            )
            body = {
                "type": order_type,
                "instrument": instrument,
                "side": side,
                "volume": str(volume),
                **priced,
            }
        if comment:
            body["comment"] = comment[:128]
        self._gate(
            confirmed=confirmed, db=db, context=context,
            stage="place_pending_order",
            title=f"Exness: {order_type} order {body.get('instrument', '')}",
            instructions="\n".join([
                "Devon wants to place a pending order on Exness.",
                f"account={account_id} order={body}",
                "Approve ONLY if the order above is exactly what you want.",
            ]),
            resume_state={"op": "place_pending_order", "body": body,
                          "idempotency_key": idempotency_key or uuid.uuid4().hex},
        )
        return self._api(
            "POST",
            f"/v1/trading/accounts/{account_id}/orders",
            host_kind="trading",
            json_body=body,
            idempotency_key=idempotency_key,
        )

    def modify_order(
        self,
        order_id: str,
        *,
        price: float | None = None,
        stop_loss: float | None = None,
        take_profit: float | None = None,
        comment: str = "",
        confirmed: bool = False,
        db: Any = None,
        context: Any = None,
    ) -> dict[str, Any]:
        """Modify a pending order's price/SL/TP. Confirmation-gated."""
        account_id, *_ = self._auth()
        order_id = (order_id or "").strip()
        if not order_id:
            raise ExnessError("empty order_id")
        body: dict[str, Any] = {}
        if price is not None:
            body["price"] = str(price)
        if stop_loss is not None:
            body["stop_loss_price"] = str(stop_loss)
        if take_profit is not None:
            body["take_profit_price"] = str(take_profit)
        if comment:
            body["comment"] = comment[:128]
        if not body:
            raise ExnessError("nothing to modify — pass price, stop_loss, "
                              "take_profit, or comment")
        self._gate(
            confirmed=confirmed, db=db, context=context, stage="modify_order",
            title=f"Exness: modify order {order_id}",
            instructions="\n".join([
                "Devon wants to modify a pending order on Exness.",
                f"account={account_id} order={order_id} changes={body}",
                "Approve ONLY if these changes are exactly what you want.",
            ]),
            resume_state={"op": "modify_order", "order_id": order_id,
                          "body": body},
        )
        return self._api(
            "PATCH",
            f"/v1/trading/accounts/{account_id}/orders/{order_id}",
            host_kind="trading",
            json_body=body,
        )

    def cancel_order(
        self,
        order_id: str,
        *,
        confirmed: bool = False,
        db: Any = None,
        context: Any = None,
    ) -> dict[str, Any]:
        """Cancel one pending order. Confirmation-gated."""
        account_id, *_ = self._auth()
        order_id = (order_id or "").strip()
        if not order_id:
            raise ExnessError("empty order_id")
        self._gate(
            confirmed=confirmed, db=db, context=context, stage="cancel_order",
            title=f"Exness: cancel order {order_id}",
            instructions="\n".join([
                "Devon wants to cancel a pending order on Exness.",
                f"account={account_id} order={order_id}",
                "Approve ONLY if this is the order you want cancelled.",
            ]),
            resume_state={"op": "cancel_order", "order_id": order_id},
        )
        return self._api(
            "DELETE",
            f"/v1/trading/accounts/{account_id}/orders/{order_id}",
            host_kind="trading",
        )

    def cancel_all_orders(
        self,
        *,
        instrument: str = "",
        order_type: str = "",
        side: str = "",
        confirmed: bool = False,
        db: Any = None,
        context: Any = None,
    ) -> dict[str, Any]:
        """Cancel pending orders matching the filters. Confirmation-gated."""
        account_id, *_ = self._auth()
        params = {
            "filter": "all",
            "instrument": instrument.strip().upper() or None,
            "order_type": order_type.strip().lower() or None,
            "side": side.strip().lower() or None,
        }
        self._gate(
            confirmed=confirmed, db=db, context=context,
            stage="cancel_all_orders",
            title="Exness: cancel pending orders",
            instructions="\n".join([
                "Devon wants to CANCEL pending orders on Exness.",
                f"account={account_id} filters={params}",
                "Approve ONLY if you really want these cancelled.",
            ]),
            resume_state={"op": "cancel_all_orders", "params": params},
        )
        return self._api(
            "DELETE",
            f"/v1/trading/accounts/{account_id}/orders",
            host_kind="trading",
            params=params,
        )

    # ── checkpoint resume ────────────────────────────────────────────

    def resume_checkpoint(self, checkpoint: Any, *, db: Any,
                          context: Any = None) -> dict[str, Any]:
        """Complete a money move after its human checkpoint resolved."""
        state = dict(getattr(checkpoint, "resume_state", None) or {})
        op = state.get("op", "")
        if state.get("stage") not in {
            "open_position", "close_position", "close_all_positions",
            "place_pending_order", "modify_order", "cancel_order",
            "cancel_all_orders",
        }:
            raise ExnessError(
                f"cannot resume checkpoint stage {state.get('stage')!r}"
            )
        fn = {
            "open_position": lambda: self.open_position(
                state["body"]["instrument"], state["body"]["side"],
                float(state["body"]["volume"]),
                price=_num(state["body"].get("price")),
                stop_loss=_num(state["body"].get("stop_loss_price")),
                take_profit=_num(state["body"].get("take_profit_price")),
                comment=state["body"].get("comment", ""),
                idempotency_key=state.get("idempotency_key"),
                confirmed=True, db=db, context=context),
            "close_position": lambda: self.close_position(
                state["position_id"],
                volume=_num((state.get("params") or {}).get("volume")),
                confirmed=True, db=db, context=context),
            "close_all_positions": lambda: self.close_all_positions(
                confirmed=True, db=db, context=context,
                **{k: v for k, v in (state.get("params") or {}).items()
                   if k in ("instrument", "side") and v}),
            "place_pending_order": lambda: self.place_pending_order(
                state["body"]["type"],
                instrument=state["body"].get("instrument", ""),
                side=state["body"].get("side", ""),
                volume=float(state["body"].get("volume", 0) or 0),
                price=_num(state["body"].get("price")),
                stop_loss=_num(state["body"].get("stop_loss_price")),
                take_profit=_num(state["body"].get("take_profit_price")),
                position_id=state["body"].get("position_id", ""),
                comment=state["body"].get("comment", ""),
                idempotency_key=state.get("idempotency_key"),
                confirmed=True, db=db, context=context),
            "modify_order": lambda: self.modify_order(
                state["order_id"],
                price=_num(state["body"].get("price")),
                stop_loss=_num(state["body"].get("stop_loss_price")),
                take_profit=_num(state["body"].get("take_profit_price")),
                comment=state["body"].get("comment", ""),
                confirmed=True, db=db, context=context),
            "cancel_order": lambda: self.cancel_order(
                state["order_id"], confirmed=True, db=db, context=context),
            "cancel_all_orders": lambda: self.cancel_all_orders(
                confirmed=True, db=db, context=context,
                **{k: v for k, v in (state.get("params") or {}).items()
                   if k in ("instrument", "order_type", "side") and v}),
        }[op]
        return fn()


def _num(value: Any) -> float | None:
    try:
        return float(value) if value is not None else None
    except (TypeError, ValueError):
        return None
