"""Legal information surface — never legal advice."""

from .contracts import (
    DISCLAIMER,
    CONTRACT_TYPES,
    REVIEW_STYLES,
    CLAUSE_CATEGORIES,
    Finding,
    Review,
    ReviewDiff,
    ContractMeta,
    control_contract,
    compare_reviews,
    detect_contract_type,
    extract_clauses,
    extract_metadata,
    extract_rights,
    categorize_clauses,
    format_diff,
    format_review,
    information_only_check,
    plain_english,
    review_contract,
)

from .aid import (
    LANGUAGES,
    LANGUAGE_NAMES,
    ANSWER_STYLES,
    Answer,
    answer_legal_question,
    bill_answer,
    chunk_for_sms,
    control_legal,
    corpus_search,
    format_answer,
    format_answer_sms,
    letter_kinds,
    refer_lawyer,
    render_letter,
    triage,
)

from .research import (
    CONFIDENTIALITY,
    RESEARCH_STYLES,
    Citation,
    Evidence,
    LegalResearch,
    ResearchResult,
    control_research,
    expand_query,
    format_research,
    groundedness,
    research_citations,
    verify_citations,
)

from .portfolio import (
    PORTFOLIO_CHECK_ACTION,
    PORTFOLIO_CRON,
    RENEWAL_BUCKETS,
    Contract,
    Obligation,
    SLAStatus,
    TimelineEvent,
    ContractPortfolio,
    check_all as portfolio_check_all,
    control_contracts,
    ensure_schedule as ensure_portfolio_schedule,
)

from .regulatory import (
    REGCHECK_ACTION,
    REGCHECK_CRON,
    REGULATORS,
    REGULATORY_CALENDAR,
    ALERT_STYLES,
    Control,
    OBLIGATION_CONTROLS,
    RegWatch,
    RegulatoryItem,
    RegulatoryWatch,
    alert_text,
    check_all as regulatory_check_all,
    control_regwatch,
    controls_for,
    impact_score,
    sync_calendar_to_portfolio,
    upcoming_deadlines,
    ensure_schedule as ensure_regulatory_schedule,
)

__all__ = [
    "DISCLAIMER",
    "CONTRACT_TYPES",
    "REVIEW_STYLES",
    "CLAUSE_CATEGORIES",
    "Finding",
    "Review",
    "ReviewDiff",
    "ContractMeta",
    "control_contract",
    "compare_reviews",
    "detect_contract_type",
    "extract_clauses",
    "extract_metadata",
    "extract_rights",
    "categorize_clauses",
    "format_diff",
    "format_review",
    "information_only_check",
    "plain_english",
    "review_contract",
    "LANGUAGES",
    "LANGUAGE_NAMES",
    "ANSWER_STYLES",
    "Answer",
    "answer_legal_question",
    "bill_answer",
    "chunk_for_sms",
    "control_legal",
    "corpus_search",
    "format_answer",
    "format_answer_sms",
    "letter_kinds",
    "refer_lawyer",
    "render_letter",
    "triage",
    "CONFIDENTIALITY",
    "RESEARCH_STYLES",
    "Citation",
    "Evidence",
    "LegalResearch",
    "ResearchResult",
    "control_research",
    "expand_query",
    "format_research",
    "groundedness",
    "research_citations",
    "verify_citations",
    "PORTFOLIO_CHECK_ACTION",
    "PORTFOLIO_CRON",
    "RENEWAL_BUCKETS",
    "Contract",
    "Obligation",
    "SLAStatus",
    "TimelineEvent",
    "ContractPortfolio",
    "portfolio_check_all",
    "control_contracts",
    "ensure_portfolio_schedule",
    "REGCHECK_ACTION",
    "REGCHECK_CRON",
    "REGULATORS",
    "REGULATORY_CALENDAR",
    "ALERT_STYLES",
    "Control",
    "OBLIGATION_CONTROLS",
    "RegWatch",
    "RegulatoryItem",
    "RegulatoryWatch",
    "alert_text",
    "regulatory_check_all",
    "control_regwatch",
    "controls_for",
    "impact_score",
    "sync_calendar_to_portfolio",
    "upcoming_deadlines",
    "ensure_regulatory_schedule",
]
