"""Legal information surface — never legal advice."""

from .contracts import (
    DISCLAIMER,
    CONTRACT_TYPES,
    Finding,
    Review,
    control_contract,
    detect_contract_type,
    extract_clauses,
    format_review,
    information_only_check,
    review_contract,
)

from .aid import (
    LANGUAGES,
    LANGUAGE_NAMES,
    Answer,
    answer_legal_question,
    bill_answer,
    control_legal,
    corpus_search,
    format_answer,
)

from .research import (
    CONFIDENTIALITY,
    Citation,
    Evidence,
    LegalResearch,
    ResearchResult,
    control_research,
    format_research,
    research_citations,
)

from .portfolio import (
    PORTFOLIO_CHECK_ACTION,
    PORTFOLIO_CRON,
    Contract,
    Obligation,
    SLAStatus,
    TimelineEvent,
    ContractPortfolio,
    check_all as portfolio_check_all,
    control_contracts,
    ensure_schedule as ensure_portfolio_schedule,
)

__all__ = [
    "DISCLAIMER",
    "CONTRACT_TYPES",
    "Finding",
    "Review",
    "control_contract",
    "detect_contract_type",
    "extract_clauses",
    "format_review",
    "information_only_check",
    "review_contract",
    "LANGUAGES",
    "LANGUAGE_NAMES",
    "Answer",
    "answer_legal_question",
    "bill_answer",
    "control_legal",
    "corpus_search",
    "format_answer",
    "CONFIDENTIALITY",
    "Citation",
    "Evidence",
    "LegalResearch",
    "ResearchResult",
    "control_research",
    "format_research",
    "research_citations",
    "PORTFOLIO_CHECK_ACTION",
    "PORTFOLIO_CRON",
    "Contract",
    "Obligation",
    "SLAStatus",
    "TimelineEvent",
    "ContractPortfolio",
    "portfolio_check_all",
    "control_contracts",
    "ensure_portfolio_schedule",
]
