"""Scaffold new niche plugins — generates a working, importable skeleton."""

from __future__ import annotations

import re
from pathlib import Path

from .registry import register

_SKELETON = '''"""Niche plugin: {name} — {thesis_placeholder}

Generated by nomorals.media.contentops.niches.scaffold.
Fill in the three marked sections, then import this module — it
self-registers on import, no core changes needed.
"""

from __future__ import annotations

from nomorals.media.contentops.niches.base import NichePlugin, VisualPlan, VoiceSpec
from nomorals.media.contentops.niches.registry import register


class {classname}(NichePlugin):
    name = "{name}"
    thesis = "{thesis_placeholder}"
    cadence = {cadence}
    target_seconds = (25, 55)

    # ── 1. RETENTION-ENGINEERED SCRIPT PROMPT ──────────────────────────
    # Enforce: hook in the first 2 s, an open loop, a payoff, spoken-only
    # text (no stage directions, no "hey guys"), and a strict word budget
    # for 25–55 s at this niche's pace.

    def script_prompt(self, topic: str) -> str:
        lo, hi = self.word_budget()
        return f"""\\
You are a short-form scriptwriter for the {name} niche.

TOPIC: {{topic}}

Write a spoken-word script, {{lo}}–{{hi}} words, for a vertical short.
RULES:
- FIRST LINE is the hook — a curiosity gap, a bold claim, or a pattern
  interrupt. No greetings, no "welcome back", no setup throat-clearing.
- Every 3–5 seconds add a retention beat: a new detail, a twist, a
  question left hanging (open loop), then pay it off near the end.
- Plain spoken text only. No stage directions, no [brackets], no emojis.
- One idea per script. End on a line worth rewatching or sharing.
- Match the niche voice: TODO — describe the {name} voice here
  (e.g. blunt second-person, cinematic narrator, deadpan…).

Return ONLY the script text.
"""

    # ── 2. VISUAL STRATEGY (original/AI visuals, style-locked) ─────────
    # Keep the style_lock stable across every video in this niche — it is
    # what makes the channel look like one channel.

    _STYLE = "TODO: immutable style anchor, e.g. \\"cinematic film still, teal-and-orange grade, 35mm\\""

    _SCENES = (
        "TODO: beat 1 visual — the hook frame",
        "TODO: beat 2 visual — escalation",
        "TODO: beat 3 visual — the payoff frame",
    )

    def visual_strategy(self, script: str) -> VisualPlan:
        return self._beats_to_scenes(
            script,
            self._SCENES,
            style_lock=self._STYLE,
            motions=("zoom-in-slow", "pan-right-slow", "zoom-out-slow"),
            notes=f"{{self.name}} visual plan",
        )

    # ── 3. PACKAGING ───────────────────────────────────────────────────

    title_template = "TODO {{topic}} TODO"
    description_template = "{{topic}}\\n\\nTODO one-line tease + CTA.\\n\\n{{script}}"
    hashtags = {{"tiktok": ["#TODO"], "youtube": ["#TODO"], "instagram": ["#TODO"]}}
    voice_spec = VoiceSpec(preferred_voice="", mood="neutral", intensity=3, pace_wpm=150)

    ypp_rationale = (
        "TODO: why this niche is monetization-safe — original AI visuals, "
        "original commentary, transformative editing."
    )


register({classname}())
'''


def scaffold(name: str, *, dest_dir: str | Path | None = None,
             thesis: str = "TODO: one-line content thesis",
             cadence: float = 1.0,
             overwrite: bool = False) -> str:
    """Generate a working plugin skeleton file for niche ``name``.

    Writes ``<name>.py`` into the niches package (or ``dest_dir``), ready
    to import and register. Returns the written file path. The skeleton
    imports cleanly and self-registers — validation passes once the TODO
    sections are filled in with real content.
    """
    name = (name or "").strip().lower()
    if not re.match(r"^[a-z0-9_]+$", name):
        raise ValueError(f"niche name must be a lowercase slug, got {name!r}")
    package_dir = Path(__file__).resolve().parent
    target = Path(dest_dir) if dest_dir else package_dir
    path = target / f"{name}.py"
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists (pass overwrite=True)")
    classname = "".join(part.capitalize() for part in name.split("_")) + "Niche"
    content = _SKELETON.format(
        name=name,
        classname=classname,
        thesis_placeholder=thesis.replace('"', "'"),
        cadence=cadence,
    )
    path.write_text(content, encoding="utf-8")
    return str(path)
