"""Exness connector tests. HTTP is fully mocked — no network.

Covers: the native RFC 8032 Ed25519 (verified against a signature +
public key generated by the independent ``cryptography`` implementation,
NOT against itself), private-seed parsing, the EXN-* signing envelope,
connect/status/test_connection, market data reads, the money-move
confirmation gate, and checkpoint resume.
"""

from __future__ import annotations

import base64
import json
import unittest
from typing import Any
from unittest import mock

from nomorals.accounts.vault import CredentialVault
from nomorals.connectors.base import ConnectorError
from nomorals.connectors.exness import (
    ExnessConnector,
    ExnessError,
    _parse_private_seed,
    ed25519_publickey,
    ed25519_sign,
)
from nomorals.connectors.registry import get_connector
from nomorals.storage.db import Database

# ── independent test vector ──────────────────────────────────────────
# Generated once with the ``cryptography`` package's Ed25519
# (Ed25519PrivateKey.from_private_bytes(seed).sign(msg)); hard-coded here
# so the suite never depends on a third-party crypto lib at runtime.
_VEC_SEED = bytes(range(32))
_VEC_MSG = (
    b'{"api_key":"test","idempotency_key":"abc","timestamp":1728460000000,'
    b'"sign_version":1,"method":"GET",'
    b'"path":"/v1/configuration/accounts/123/account",'
    b'"body_hash":"47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="}'
)
_VEC_SIG = bytes.fromhex(
    "ef111992fec6f27e142d0d7338ebe913657338f47e1a465be4a2abb01dae7634"
    "596525fbc529502675ce6fd9169f7138ab8622869041c37b21f6580d98a4b507"
)
_VEC_PUB = bytes.fromhex(
    "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
)

_SEED_B64URL = base64.urlsafe_b64encode(bytes(range(32))).rstrip(b"=").decode()
_SEED_HEX = bytes(range(32)).hex()


def _vault() -> CredentialVault:
    return CredentialVault(Database(":memory:"), master_passphrase="test")


class FakeResponse:
    def __init__(self, status: int = 200, payload: Any = None,
                 headers: dict | None = None) -> None:
        self.status = status
        self._payload = payload
        self.headers = headers or {}
        self.url = ""

    @property
    def ok(self) -> bool:
        return 200 <= self.status < 300

    def json(self) -> Any:
        return self._payload


class FakeHttp:
    """Scripted stand-in for HttpClient. No network."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, str, Any, Any]] = []
        self.routes: list[tuple[str, str, FakeResponse]] = []

    def route(self, method: str, path: str, response: FakeResponse) -> None:
        self.routes.append((method.upper(), path, response))

    def request(self, method: str, url: str, data: Any = None,
                headers: Any = None, **kw: Any) -> FakeResponse:
        self.calls.append((method.upper(), url, data, headers))
        for rm, rp, resp in sorted(self.routes, key=lambda r: -len(r[1])):
            if rm == method.upper() and rp in url:
                return resp
        return FakeResponse(404, {"error_message": "not mocked", "code": 3})


def _exness(http: FakeHttp | None = None) -> tuple[ExnessConnector, FakeHttp]:
    http = http or FakeHttp()
    return ExnessConnector(_vault(), http=http), http


def _connected(http: FakeHttp | None = None) -> tuple[ExnessConnector, FakeHttp]:
    conn, http = _exness(http)
    http.route("GET", "/v1/configuration/accounts/1042/account",
               FakeResponse(200, {"account_id": "1042",
                                  "settings": {"currency": "USD"}}))
    result = conn.connect(api_key="exn_test_key", private_key=_SEED_B64URL,
                          account_id="1042")
    assert result.ok
    return conn, http


class Ed25519Test(unittest.TestCase):
    def test_vector_matches_independent_implementation(self):
        self.assertEqual(ed25519_sign(_VEC_SEED, _VEC_MSG), _VEC_SIG)
        self.assertEqual(ed25519_publickey(_VEC_SEED), _VEC_PUB)

    def test_sign_is_deterministic(self):
        self.assertEqual(ed25519_sign(_VEC_SEED, _VEC_MSG),
                         ed25519_sign(_VEC_SEED, _VEC_MSG))

    def test_different_messages_different_signatures(self):
        self.assertNotEqual(ed25519_sign(_VEC_SEED, b"a"),
                            ed25519_sign(_VEC_SEED, b"b"))

    def test_bad_seed_length(self):
        with self.assertRaises(ValueError):
            ed25519_sign(b"short", b"msg")
        with self.assertRaises(ValueError):
            ed25519_publickey(b"")


class SeedParsingTest(unittest.TestCase):
    def test_base64url_no_padding(self):
        self.assertEqual(_parse_private_seed(_SEED_B64URL), bytes(range(32)))

    def test_hex(self):
        self.assertEqual(_parse_private_seed(_SEED_HEX), bytes(range(32)))

    def test_standard_base64(self):
        b64 = base64.b64encode(bytes(range(32))).decode()
        self.assertEqual(_parse_private_seed(b64), bytes(range(32)))

    def test_garbage_rejected(self):
        with self.assertRaises(ExnessError):
            _parse_private_seed("not-a-key!!!")


class SigningEnvelopeTest(unittest.TestCase):
    def test_headers_shape(self):
        conn, _http = _exness()
        headers = conn._signed_headers(
            "key123", bytes(range(32)), "POST",
            "/v1/trading/accounts/1042/positions", b'{"a":1}', "idem-1",
        )
        for name in ("EXN-API-KEY", "EXN-TIMESTAMP", "EXN-SIGN-VERSION",
                     "EXN-IDEMPOTENCY-KEY", "EXN-DATA", "EXN-SIGN"):
            self.assertIn(name, headers)
        self.assertEqual(headers["EXN-API-KEY"], "key123")
        self.assertEqual(headers["EXN-SIGN-VERSION"], "1")
        self.assertEqual(headers["EXN-IDEMPOTENCY-KEY"], "idem-1")
        payload = json.loads(
            base64.urlsafe_b64decode(headers["EXN-DATA"] + "=="))
        self.assertEqual(payload["method"], "POST")
        self.assertEqual(payload["path"],
                         "/v1/trading/accounts/1042/positions")
        self.assertEqual(payload["sign_version"], 1)
        # timestamp is biased into the past (asymmetric server tolerance)
        import time as _t
        self.assertLess(int(headers["EXN-TIMESTAMP"]), int(_t.time() * 1000))


class LifecycleTest(unittest.TestCase):
    def test_registered(self):
        self.assertIs(get_connector("exness"), ExnessConnector)

    def test_connect_ok(self):
        conn, http = _exness()
        http.route("GET", "/v1/configuration/accounts/1042/account",
                   FakeResponse(200, {"account_id": "1042",
                                      "settings": {"currency": "USD"}}))
        result = conn.connect(api_key="exn_test_key",
                              private_key=_SEED_B64URL, account_id="1042")
        self.assertTrue(result.ok)
        self.assertIn("1042", result.account)
        self.assertIn("DEMO", result.message)

    def test_connect_rejects_bad_key(self):
        conn, http = _exness()
        http.route("GET", "/v1/configuration/accounts/1042/account",
                   FakeResponse(200, {"error_message": "bad key",
                                      "code": 1000}))
        with self.assertRaises(ExnessError):
            conn.connect(api_key="bad", private_key=_SEED_B64URL,
                         account_id="1042")

    def test_connect_twice_refused(self):
        conn, _http = _connected()
        with self.assertRaises(ConnectorError):
            conn.connect(api_key="x", private_key=_SEED_B64URL,
                         account_id="1042")

    def test_status_not_connected(self):
        conn, _http = _exness()
        st = conn.status()
        self.assertFalse(st.connected)
        self.assertIn("exness", st.detail)

    def test_status_connected(self):
        conn, http = _connected()
        http.route("GET", "/v1/trading/access-point",
                   FakeResponse(200, {"access_point": "https://t.exness.com",
                                      "account_id": "1042"}))
        http.route("GET", "/v1/trading/accounts/1042/snapshot",
                   FakeResponse(200, {"account_state": {"balance": "1000.5",
                                                       "equity": "1002.0",
                                                       "used_margin": "10.0"},
                                      "positions": [{"position_id": "1"}],
                                      "orders": []}))
        st = conn.status()
        self.assertTrue(st.connected)
        self.assertIn("1042", st.account or "")
        self.assertIn("1000.5", st.detail)

    def test_status_bad_key_is_honest(self):
        conn, http = _connected()
        http.route("GET", "/v1/trading/access-point",
                   FakeResponse(200, {"error_message": "bad signature",
                                      "code": 1001}))
        st = conn.status()
        self.assertFalse(st.connected)

    def test_test_connection(self):
        conn, http = _connected()
        http.route("GET", "/v1/trading/access-point",
                   FakeResponse(200, {"access_point": "https://t.exness.com",
                                      "account_id": "1042"}))
        http.route("GET", "/v1/trading/accounts/1042/snapshot",
                   FakeResponse(200, {"account_state": {}}))
        self.assertTrue(conn.test_connection())

    def test_disconnect(self):
        conn, _http = _connected()
        conn.disconnect()
        self.assertFalse(conn.status().connected)


class MarketDataTest(unittest.TestCase):
    def test_get_candles(self):
        conn, http = _connected()
        http.route("GET", "/v1/market-data/accounts/1042/candles",
                   FakeResponse(200, {"candles": [
                       {"time": "2026-10-09T00:00:00Z", "open": 1.1,
                        "high": 1.2, "low": 1.0, "close": 1.15,
                        "volume": 42}]}))
        candles = conn.get_candles("EURUSD", "H1", count=10)
        self.assertEqual(len(candles), 1)
        self.assertEqual(candles[0]["close"], 1.15)
        method, url, _data, headers = http.calls[-1]
        self.assertEqual(method, "GET")
        self.assertIn("instrument=EURUSD", url)
        self.assertIn("EXN-SIGN", headers)

    def test_get_instruments(self):
        conn, http = _connected()
        http.route("GET", "/v1/configuration/accounts/1042/instruments",
                   FakeResponse(200, {"instruments": ["EURUSD", "XAUUSD"]}))
        self.assertEqual(conn.get_instruments(), ["EURUSD", "XAUUSD"])

    def test_orders_history(self):
        conn, http = _connected()
        http.route("GET", "/v1/history/accounts/1042/orders",
                   FakeResponse(200, {"items": [], "has_more": False}))
        out = conn.orders_history(limit=10)
        self.assertEqual(out["items"], [])


class MoneyGateTest(unittest.TestCase):
    def _trading_routes(self, http: FakeHttp) -> None:
        http.route("GET", "/v1/trading/access-point",
                   FakeResponse(200, {"access_point": "https://t.exness.com",
                                      "account_id": "1042"}))
        http.route("POST", "/v1/trading/accounts/1042/positions",
                   FakeResponse(200, {"status": "accepted",
                                      "operation_id": "op-1"}))
        http.route("GET",
                   "/v1/configuration/accounts/1042/instruments/EURUSD/conditions",
                   FakeResponse(200, {"instrument": "EURUSD",
                                      "point_digits": 5}))

    def test_open_position_needs_confirmation(self):
        conn, _http = _connected()
        with self.assertRaises(ConnectorError) as ctx:
            conn.open_position("EURUSD", "buy", 0.01)
        self.assertIn("confirmation", str(ctx.exception))

    def test_open_position_confirmed(self):
        conn, http = _connected()
        self._trading_routes(http)
        out = conn.open_position("EURUSD", "buy", 0.01, stop_loss=1.05,
                                 take_profit=1.20, confirmed=True)
        self.assertEqual(out["operation_id"], "op-1")
        method, url, data, headers = http.calls[-1]
        self.assertEqual(method, "POST")
        self.assertIn("/positions", url)
        body = json.loads(data.decode())
        self.assertEqual(body["instrument"], "EURUSD")
        self.assertEqual(body["side"], "buy")
        # prices rounded to the instrument's 5 point digits
        self.assertEqual(body["stop_loss_price"], "1.05000")
        self.assertEqual(body["take_profit_price"], "1.20000")
        self.assertIn("EXN-SIGN", headers)
        self.assertTrue(headers["EXN-IDEMPOTENCY-KEY"])

    def test_close_position_needs_confirmation(self):
        conn, _http = _connected()
        with self.assertRaises(ConnectorError):
            conn.close_position("pos-9")

    def test_pending_order_validation(self):
        conn, http = _connected()
        with self.assertRaises(ExnessError):
            conn.place_pending_order("limit", "EURUSD", "buy", 0.01,
                                     confirmed=True)  # no price

    def test_resume_checkpoint_rejects_unknown_stage(self):
        conn, _http = _connected()
        cp = mock.Mock()
        cp.resume_state = {"stage": "nope", "op": "nope"}
        with self.assertRaises(ExnessError):
            conn.resume_checkpoint(cp, db=object())


if __name__ == "__main__":
    unittest.main()
