"""Plugin package model: manifests, registry, sandboxed loading."""

from __future__ import annotations

from .errors import (
    AlreadyInstalled,
    DependencyError,
    IncompatibleEngine,
    LoadError,
    ManifestError,
    NotInstalled,
    PermissionDenied,
    PluginError,
    PluginTimeout,
)
from .loader import (
    HookCall,
    HookResults,
    LoadedPlugin,
    PluginCapabilities,
    PluginConfig,
    PluginHookBus,
    call_entry,
    load_plugin,
    unload_plugin,
)
from .manifest import (
    DEFAULT_LIMITS,
    KNOWN_PERMISSIONS,
    LIFECYCLE_HOOKS,
    MANIFEST_FILENAME,
    ContributedCommand,
    ContributedTool,
    PluginDependency,
    PluginHook,
    PluginManifest,
    load_manifest,
    load_manifest_file,
    parse_version_spec,
    satisfies_version,
    validate_against_schema,
    version_key,
)
from .registry import InstalledPlugin, PluginRegistry
from .render import (
    THEMES,
    render_health,
    render_plugin_card,
    render_plugin_table,
)
from .wiring import (
    PluginKV,
    make_audit,
    make_fetcher,
    make_notifier,
    purge_plugin_data,
    wire_capabilities,
)

__all__ = [
    "AlreadyInstalled",
    "ContributedCommand",
    "ContributedTool",
    "DEFAULT_LIMITS",
    "DependencyError",
    "HookCall",
    "HookResults",
    "IncompatibleEngine",
    "InstalledPlugin",
    "KNOWN_PERMISSIONS",
    "LIFECYCLE_HOOKS",
    "LoadError",
    "LoadedPlugin",
    "MANIFEST_FILENAME",
    "ManifestError",
    "NotInstalled",
    "PermissionDenied",
    "PluginCapabilities",
    "PluginConfig",
    "PluginDependency",
    "PluginError",
    "PluginHook",
    "PluginHookBus",
    "PluginKV",
    "PluginManifest",
    "PluginRegistry",
    "PluginTimeout",
    "THEMES",
    "call_entry",
    "load_manifest",
    "load_manifest_file",
    "load_plugin",
    "make_audit",
    "make_fetcher",
    "make_notifier",
    "parse_version_spec",
    "purge_plugin_data",
    "render_health",
    "render_plugin_card",
    "render_plugin_table",
    "satisfies_version",
    "unload_plugin",
    "validate_against_schema",
    "version_key",
    "wire_capabilities",
]
