"""L3 — partner: the romantic-companion cognition core.

The persona is data, the mood is a persistent state machine, the relationship
is a long-arc record, and the background knowledge is gated context — nothing
in this package *talks*. Talking happens in L5 (``agents/partner/``)
through the LLM router; this package decides *who she is and how she feels*.

    from nomorals.partner import (
        Persona, MoodEngine, Relationship, BackgroundSelector,
        PartnerResponder, PartnerContextBuilder, detect_signals,
    )
"""

from __future__ import annotations

from .affect import (
    AFFECT_CATEGORIES,
    AFFECT_EVENT_CAP,
    AffectReading,
    AffectScorer,
    affect_to_events,
    score_affect,
)
from .background import BackgroundFact, BackgroundPack, BackgroundSelector, GATE_MODES
from .chat_profile import build_context_lines, get_profile, refresh_profile
from .context import PLATFORM_NOTES, SHRINK_ORDER, PartnerContextBuilder
from .gating import (
    MODE_GROUP,
    MODE_OWNER,
    MODE_PRIVATE,
    classify_chat,
    gate_block,
    gate_decision,
    is_restricted,
    relationship_block_for,
)
from .group_roles import (
    ROLE_ADMIN,
    ROLE_MEMBER,
    ROLE_UNKNOWN,
    clear_role_cache,
    resolve_group_role,
)
from .lexicon_feed import CATEGORIES as LEXICON_CATEGORIES
from .lexicon_feed import LEXICON_MODULE, LexiconFeed, seed_partner_lexicon
from .mood import (
    DIMENSIONS,
    EVENT_TABLE,
    MOOD_LABELS,
    MOOD_PAD,
    EmotionSpike,
    MoodEngine,
    MoodEvent,
    MoodState,
)
from .persona import (
    BIG_FIVE_TRAITS,
    DEFAULT_BASLINES,
    DialogueExample,
    Persona,
    SpeechProfile,
    default_persona,
    persona_from_dict,
)
from .presence import (
    TYPING_KEEPALIVE_S,
    Presence,
    TypingPlan,
    decide_presence,
    human_typing_seconds,
    is_low_content,
    read_delay_seconds,
    thinking_typing_seconds,
    typing_schedule,
)
from .relationship import ARC_AXES, DEFAULT_AXES, STAGES, Relationship
from .responder import FALLBACK_LINES, PartnerResponder, ReplyBundle, Signal, detect_signals
from .social_gate import (
    ACTOR_GROUP_ADMIN,
    ACTOR_OUTSIDER,
    ACTOR_OWNER,
    ADMIN_GROUP_TOOLS,
    CAPABILITY_MATRIX,
    PRIVATE_CATEGORIES,
    PUBLIC_CATEGORIES,
    DenialLog,
    DenialRecord,
    SocialGrant,
    audit_matrix,
    check_tool_call,
    default_denial_log,
    grant_for,
    recent_denials,
)
from .style import (
    VOICE_THEMES,
    GuardVerdict,
    apply_texting_voice,
    apply_voice_theme,
    clamp_to_budget,
    length_budget,
    lexicon_hits,
    parrot_check,
    repair_echo,
    should_answer_short,
    split_messages,
    strip_robotic,
)

__all__ = [
    "ACTOR_GROUP_ADMIN",
    "ACTOR_OUTSIDER",
    "ACTOR_OWNER",
    "ADMIN_GROUP_TOOLS",
    "AFFECT_CATEGORIES",
    "AFFECT_EVENT_CAP",
    "ARC_AXES",
    "AffectReading",
    "AffectScorer",
    "BIG_FIVE_TRAITS",
    "BackgroundFact",
    "BackgroundPack",
    "BackgroundSelector",
    "CAPABILITY_MATRIX",
    "DEFAULT_AXES",
    "DEFAULT_BASLINES",
    "DIMENSIONS",
    "DenialLog",
    "DenialRecord",
    "DialogueExample",
    "EVENT_TABLE",
    "FALLBACK_LINES",
    "GATE_MODES",
    "GuardVerdict",
    "LEXICON_CATEGORIES",
    "LEXICON_MODULE",
    "LexiconFeed",
    "MODE_GROUP",
    "MODE_OWNER",
    "MODE_PRIVATE",
    "MOOD_LABELS",
    "MOOD_PAD",
    "PLATFORM_NOTES",
    "PRIVATE_CATEGORIES",
    "PUBLIC_CATEGORIES",
    "PartnerContextBuilder",
    "PartnerResponder",
    "Persona",
    "Presence",
    "ReplyBundle",
    "Relationship",
    "ROLE_ADMIN",
    "ROLE_MEMBER",
    "ROLE_UNKNOWN",
    "SHRINK_ORDER",
    "Signal",
    "SocialGrant",
    "STAGES",
    "SpeechProfile",
    "TYPING_KEEPALIVE_S",
    "TypingPlan",
    "VOICE_THEMES",
    "affect_to_events",
    "apply_texting_voice",
    "apply_voice_theme",
    "audit_matrix",
    "build_context_lines",
    "check_tool_call",
    "clamp_to_budget",
    "classify_chat",
    "clear_role_cache",
    "decide_presence",
    "default_denial_log",
    "default_persona",
    "detect_signals",
    "gate_block",
    "gate_decision",
    "get_profile",
    "human_typing_seconds",
    "is_low_content",
    "is_restricted",
    "length_budget",
    "lexicon_hits",
    "parrot_check",
    "persona_from_dict",
    "read_delay_seconds",
    "recent_denials",
    "refresh_profile",
    "relationship_block_for",
    "repair_echo",
    "resolve_group_role",
    "score_affect",
    "seed_partner_lexicon",
    "should_answer_short",
    "split_messages",
    "strip_robotic",
    "thinking_typing_seconds",
    "typing_schedule",
    "EmotionSpike",
    "MoodEngine",
    "MoodEvent",
    "MoodState",
    "grant_for",
]
