"""Waste detection for assembled context.

:class:`WasteDetector` analyzes a built context and reports reclaimable
tokens: duplicated tool outputs, near-duplicate passages, stale history
beyond the useful window, low-entropy boilerplate, and oversized low-signal
sections.  Estimates are conservative — a reported reclaimable token is one
the engine could actually remove without touching load-bearing content.

Every finding carries a ``recoverability`` label:

* ``reconstructible`` — the content can be re-fetched from a pointer
  (file paths, artifact URIs).  Cheapest to drop.
* ``reproducible`` — the content can be regenerated by re-running something
  (tool outputs, old history).  Cheap to drop.
* ``irreplaceable`` — decisions, corrections, pinned criteria.  Never waste
  by definition; flagged only so the report is honest.
"""

from __future__ import annotations

import re
import zlib
from collections import Counter
from dataclasses import dataclass, field
from typing import Any

from .engine import BuiltContext
from .budget import ContextBudget
from .sections import Section, token_count

__all__ = [
    "WasteFinding",
    "WasteReport",
    "WasteDetector",
    "classify_recoverability",
    "simhash",
]

_WS_RE = re.compile(r"\s+")
_GRAM_RE = re.compile(r"[a-z0-9]{2,}")


def _normalize(text: str) -> str:
    return _WS_RE.sub(" ", text.strip().lower())


def simhash(text: str, *, gram_n: int = 3) -> int:
    """64-bit SimHash of ``text`` over word ``gram_n``-grams.

    Pure-Python near-duplicate fingerprinting (the same family of technique
    the headroom/RTCO context optimizers use): texts that differ by a few
    words hash to values a small Hamming distance apart.
    """
    words = _GRAM_RE.findall(text.lower())
    if not words:
        return 0
    vec = [0] * 64
    for i in range(len(words) - gram_n + 1):
        import hashlib

        h = int(hashlib.md5(
            " ".join(words[i: i + gram_n]).encode("utf-8")).hexdigest(), 16)
        for bit in range(64):
            vec[bit] += 1 if (h >> bit) & 1 else -1
    out = 0
    for bit, value in enumerate(vec):
        if value > 0:
            out |= 1 << bit
    return out


def _hamming(a: int, b: int) -> int:
    return bin(a ^ b).count("1")


def classify_recoverability(section: Section) -> str:
    """How expensive it is to recover this section's content if dropped."""
    if section.load_bearing:
        return "irreplaceable"
    name = section.name
    if name in ("artifacts", "project"):
        return "reconstructible"  # pointers: URIs, paths, names
    if name in ("history", "tools", "memory"):
        return "reproducible"  # re-runnable / re-fetchable
    return "reproducible"


@dataclass
class WasteFinding:
    kind: str  # duplicate_output | near_duplicate | stale_history |
    #            oversized_section | low_entropy
    section: str
    detail: str
    wasted_tokens: int
    reclaimable_tokens: int
    recoverability: str = "reproducible"

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "section": self.section,
            "detail": self.detail,
            "wasted_tokens": self.wasted_tokens,
            "reclaimable_tokens": self.reclaimable_tokens,
            "recoverability": self.recoverability,
        }


@dataclass
class WasteReport:
    findings: list[WasteFinding] = field(default_factory=list)

    @property
    def total_wasted(self) -> int:
        return sum(f.wasted_tokens for f in self.findings)

    @property
    def total_reclaimable(self) -> int:
        return sum(f.reclaimable_tokens for f in self.findings)

    def to_dict(self) -> dict[str, Any]:
        return {
            "findings": [f.to_dict() for f in self.findings],
            "total_wasted": self.total_wasted,
            "total_reclaimable": self.total_reclaimable,
        }

    def summary(self) -> str:
        if not self.findings:
            return "No context waste detected."
        lines = [
            f"Context waste: ~{self.total_wasted} tokens wasted, "
            f"~{self.total_reclaimable} reclaimable."
        ]
        for finding in self.findings:
            lines.append(
                f"- [{finding.kind}] {finding.section}: {finding.detail} "
                f"(~{finding.reclaimable_tokens} tokens reclaimable)"
            )
        return "\n".join(lines)

    def render(self, *, style: str = "plain") -> str:
        """Styled waste dashboard.

        ``style`` is ``"plain"`` (ASCII) or ``"fancy"`` (unicode bars and
        markers; no color codes — safe on any terminal).
        """
        fancy = style == "fancy"
        if not self.findings:
            return "✓ No context waste detected." if fancy else \
                "No context waste detected."
        title = "◆ Context waste" if fancy else "Context waste"
        lines = [
            title,
            f"  ~{self.total_wasted} tokens wasted, "
            f"~{self.total_reclaimable} reclaimable",
            "  " + "-" * 56,
        ]
        peak = max((f.reclaimable_tokens for f in self.findings), default=1)
        for finding in self.findings:
            ratio = finding.reclaimable_tokens / peak if peak else 0.0
            if fancy:
                bar = "█" * max(1, int(round(ratio * 14)))
                rec = {"reconstructible": "↺", "reproducible": "⟳",
                       "irreplaceable": "⚠"}.get(
                    finding.recoverability, "?")
            else:
                bar = "#" * max(1, int(round(ratio * 14)))
                rec = finding.recoverability[:4]
            lines.append(
                f"  {bar:<14} [{finding.kind}] {finding.section}: "
                f"~{finding.reclaimable_tokens} reclaimable {rec}"
            )
            lines.append(f"    {finding.detail}")
        return "\n".join(lines)


class WasteDetector:
    """Find duplicated, stale, and oversized content in a built context."""

    def __init__(
        self,
        *,
        stale_history_window: int = 10,
        min_stale_tokens: int = 100,
        low_signal_priority_below: float = 30.0,
        oversize_factor: float = 2.0,
        min_duplicate_tokens: int = 40,
        near_duplicate_distance: int = 10,
        min_near_duplicate_tokens: int = 60,
        low_entropy_ratio: float = 6.0,
        min_low_entropy_tokens: int = 120,
    ) -> None:
        self.stale_history_window = stale_history_window
        self.min_stale_tokens = min_stale_tokens
        self.low_signal_priority_below = low_signal_priority_below
        self.oversize_factor = oversize_factor
        self.min_duplicate_tokens = min_duplicate_tokens
        self.near_duplicate_distance = near_duplicate_distance
        self.min_near_duplicate_tokens = min_near_duplicate_tokens
        self.low_entropy_ratio = low_entropy_ratio
        self.min_low_entropy_tokens = min_low_entropy_tokens

    def analyze(
        self, built: BuiltContext, budget: ContextBudget | None = None
    ) -> WasteReport:
        report = WasteReport()
        report.findings.extend(self._find_duplicates(built))
        report.findings.extend(self._find_near_duplicates(built))
        report.findings.extend(self._find_low_entropy(built))
        report.findings.extend(self._find_stale_history(built))
        report.findings.extend(
            self._find_oversized(built, budget or ContextBudget.default()))
        # Reclaimable can never exceed wasted, by construction each finding
        # obeys it; sort biggest-first for readability.
        report.findings.sort(key=lambda f: f.reclaimable_tokens, reverse=True)
        return report

    # ── duplicated tool outputs ───────────────────────────────────────────
    def _find_duplicates(self, built: BuiltContext) -> list[WasteFinding]:
        findings: list[WasteFinding] = []
        for section in built.sections:
            if section.load_bearing:
                continue
            lines = [ln for ln in section.content.splitlines() if _normalize(ln)]
            counts = Counter(_normalize(ln) for ln in lines)
            for norm, count in counts.items():
                if count < 2:
                    continue
                tokens = token_count(norm)
                if tokens < self.min_duplicate_tokens:
                    continue
                extra = count - 1
                wasted = extra * tokens
                sample = next(ln for ln in lines if _normalize(ln) == norm)
                findings.append(WasteFinding(
                    kind="duplicate_output",
                    section=section.name,
                    detail=(f"{extra} duplicate cop{'y' if extra == 1 else 'ies'} of "
                            f"{sample[:80]!r}"),
                    wasted_tokens=wasted,
                    reclaimable_tokens=wasted,  # one copy stays, rest can go
                    recoverability=classify_recoverability(section),
                ))
        return findings

    # ── near-duplicate passages (SimHash) ─────────────────────────────────
    def _find_near_duplicates(self, built: BuiltContext) -> list[WasteFinding]:
        """Paragraph-level near-duplicate detection across all sections."""
        paras: list[tuple[str, str, int]] = []  # (section, text, tokens)
        for section in built.sections:
            if section.load_bearing:
                continue
            for para in section.content.split("\n\n"):
                para = para.strip()
                if not para:
                    continue
                tokens = token_count(para)
                if tokens >= self.min_near_duplicate_tokens:
                    paras.append((section.name, para, tokens))

        findings: list[WasteFinding] = []
        claimed: set[int] = set()
        hashes = [simhash(p[1]) for p in paras]
        for i in range(len(paras)):
            if i in claimed:
                continue
            group = [i]
            for j in range(i + 1, len(paras)):
                if j in claimed:
                    continue
                if _hamming(hashes[i], hashes[j]) <= self.near_duplicate_distance:
                    group.append(j)
            if len(group) < 2:
                continue
            for j in group:
                claimed.add(j)
            # Keep the longest (most complete) copy, reclaim the rest.
            group.sort(key=lambda k: paras[k][2], reverse=True)
            kept = group[0]
            reclaimed = sum(paras[k][2] for k in group[1:])
            sections = sorted({paras[k][0] for k in group})
            sample = paras[kept][1][:80].replace("\n", " ")
            section0 = next(
                s for s in built.sections if s.name == paras[kept][0])
            findings.append(WasteFinding(
                kind="near_duplicate",
                section="+".join(sections),
                detail=(f"{len(group) - 1} near-duplicate(s) of {sample!r}; "
                        f"kept the longest copy"),
                wasted_tokens=reclaimed,
                reclaimable_tokens=reclaimed,
                recoverability=classify_recoverability(section0),
            ))
        return findings

    # ── low-entropy boilerplate ───────────────────────────────────────────
    def _find_low_entropy(self, built: BuiltContext) -> list[WasteFinding]:
        """Flag highly repetitive blocks via zlib compression ratio."""
        findings: list[WasteFinding] = []
        for section in built.sections:
            if section.load_bearing or not section.content:
                continue
            raw = section.content.encode("utf-8", "replace")
            if len(raw) < 512:
                continue
            ratio = len(raw) / max(1, len(zlib.compress(raw, 6)))
            tokens = section.tokens
            if ratio >= self.low_entropy_ratio and tokens >= self.min_low_entropy_tokens:
                reclaimable = int(tokens * (1.0 - 1.0 / ratio))
                findings.append(WasteFinding(
                    kind="low_entropy",
                    section=section.name,
                    detail=(f"compression ratio {ratio:.1f}:1 — repetitive "
                            f"boilerplate; ~{reclaimable} tokens add no signal"),
                    wasted_tokens=reclaimable,
                    reclaimable_tokens=reclaimable,
                    recoverability=classify_recoverability(section),
                ))
        return findings

    # ── stale history ─────────────────────────────────────────────────────
    def _find_stale_history(self, built: BuiltContext) -> list[WasteFinding]:
        section = built.section("history")
        if section is None:
            return []
        entries = [ln for ln in section.content.splitlines()
                   if ln.strip().startswith("- [")]
        if len(entries) <= self.stale_history_window:
            return []
        stale = entries[: len(entries) - self.stale_history_window]
        stale_tokens = token_count("\n".join(stale))
        if stale_tokens < self.min_stale_tokens:
            return []
        return [WasteFinding(
            kind="stale_history",
            section="history",
            detail=(f"{len(stale)} of {len(entries)} history entries are older "
                    f"than the useful window ({self.stale_history_window})"),
            wasted_tokens=stale_tokens,
            reclaimable_tokens=stale_tokens,
            recoverability=classify_recoverability(section),
        )]

    # ── oversized low-signal sections ─────────────────────────────────────
    def _find_oversized(
        self, built: BuiltContext, budget: ContextBudget
    ) -> list[WasteFinding]:
        findings: list[WasteFinding] = []
        for section in built.sections:
            if section.load_bearing:
                continue  # load-bearing is never waste by definition
            if section.priority >= self.low_signal_priority_below:
                continue
            cap = budget.allocation_for(section.name)
            limit = int(cap * self.oversize_factor)
            tokens = section.tokens
            if tokens > limit:
                findings.append(WasteFinding(
                    kind="oversized_section",
                    section=section.name,
                    detail=(f"{tokens} tokens at priority {section.priority:g} "
                            f"vs ~{cap} token allocation"),
                    wasted_tokens=tokens - cap,
                    reclaimable_tokens=tokens - cap,
                    recoverability=classify_recoverability(section),
                ))
        return findings
