"""Devon as tutor — Socratic tutoring, photo input, mistake notebook.

Build-map #46. ``tutor.py`` is the dialogue engine (socratic vs direct
modes, BKT mastery model, EMT expectation/misconception cycle, answer-guard);
``flashcards.py`` turns wrong answers into FSRS-scheduled flashcards.
``dialect.py`` is the Ekiti/Ilawe Ekiti flagship dialect tutor.
``curriculum.py`` is the WAEC/JAMB wedge: syllabus grounding, course
generation, misconception bank from Chief Examiners' Reports, timed exam
simulation, and study plans.
"""

from .curriculum import (
    EXAM_FORMATS,
    MISCONCEPTION_BANK,
    Misconception,
    SCOPING_QUESTIONS,
    SUBJECTS,
    SYLLABI,
    WAEC_GRADES,
    Course,
    CourseScope,
    ExamSim,
    Lesson,
    StudyPlan,
    SyllabusTopic,
    answer_scope,
    build_course,
    clear_pending_scope,
    course_to_anki_tsv,
    course_tutor,
    courses_dir,
    curriculum_order,
    find_topic,
    misconceptions_for,
    pending_scope,
    plans_dir,
    scoping_prompt,
    set_pending_scope,
    storyboard,
    study_plan,
    subject_topics,
    syllabus_code,
    syllabus_coverage,
    waec_grade,
)
from .dialect import (
    EKITI_DIALECT_NOTES,
    MINIMAL_PAIR_SETS,
    NASAL_MINIMAL_PAIRS,
    DialectError,
    DialectTurn,
    DialectUnsupported,
    EkitiTutor,
    PhonemeFeedback,
    PronunciationReport,
    WordFeedback,
    arm_check,
    consume_check,
    detect_dialect_detail,
    get_tutor,
    mid_tone_diagnosis,
    pending_check,
    suggest_ekiti_fix,
    tonal_note_for,
    tone_pattern,
)
from .flashcards import (
    FSRS,
    FSRSCardState,
    FSRS_DEFAULT_W,
    MistakeCard,
    MistakeNotebook,
    card_from_mistake,
    grade_for_verdict,
    notebooks_dir,
)
from .tutor import (
    BKT_DEFAULTS,
    Expectation,
    MasteryModel,
    Misconception as TutorMisconception,
    QuestionScript,
    SocraticEngine,
    TutorError,
    TutorSession,
    TutorTurn,
    end_session,
    get_notebook,
    get_session,
    persist_session,
    restore_session,
    sessions_dir,
    set_session,
    tutor_from_files,
    tutor_from_photo,
)

__all__ = [
    "MasteryModel",
    "BKT_DEFAULTS",
    "MistakeNotebook",
    "MistakeCard",
    "FSRS",
    "FSRSCardState",
    "FSRS_DEFAULT_W",
    "SocraticEngine",
    "TutorError",
    "TutorSession",
    "TutorTurn",
    "Expectation",
    "Misconception",
    "TutorMisconception",
    "QuestionScript",
    "DialectError",
    "DialectTurn",
    "DialectUnsupported",
    "EkitiTutor",
    "PhonemeFeedback",
    "PronunciationReport",
    "WordFeedback",
    "SyllabusTopic",
    "SYLLABI",
    "SUBJECTS",
    "CourseScope",
    "SCOPING_QUESTIONS",
    "Lesson",
    "Course",
    "ExamSim",
    "StudyPlan",
    "EXAM_FORMATS",
    "WAEC_GRADES",
    "MISCONCEPTION_BANK",
    "EKITI_DIALECT_NOTES",
    "MINIMAL_PAIR_SETS",
    "NASAL_MINIMAL_PAIRS",
    "arm_check",
    "card_from_mistake",
    "consume_check",
    "detect_dialect_detail",
    "get_tutor",
    "grade_for_verdict",
    "mid_tone_diagnosis",
    "notebooks_dir",
    "pending_check",
    "suggest_ekiti_fix",
    "tonal_note_for",
    "tone_pattern",
    "answer_scope",
    "build_course",
    "clear_pending_scope",
    "course_to_anki_tsv",
    "course_tutor",
    "courses_dir",
    "curriculum_order",
    "end_session",
    "find_topic",
    "get_notebook",
    "get_session",
    "misconceptions_for",
    "pending_scope",
    "plans_dir",
    "persist_session",
    "restore_session",
    "scoping_prompt",
    "sessions_dir",
    "set_pending_scope",
    "set_session",
    "storyboard",
    "study_plan",
    "subject_topics",
    "syllabus_code",
    "syllabus_coverage",
    "tutor_from_files",
    "tutor_from_photo",
    "waec_grade",
]
