"""Property intelligence: rental scam detection, passports, valuations."""

from nomorals.property.scam import (
    AREA_NORMS,
    ILLEGAL_FEE_TERMS,
    ScamFlag,
    ScamReport,
    ScamStore,
    check_listing,
    control_scamcheck,
)
from nomorals.property.passport import (
    AFFORDABILITY_RATIO,
    AGENCY_PCT,
    LEGAL_PCT,
    INCOME_BANDS,
    ATTESTATION_VALID_DAYS,
    NIGERIA_KYC_DOCS,
    CostBreakdown,
    DocRef,
    RentalHistory,
    RentalPassport,
    Reference,
    PassportStore,
    affordability,
    can_afford,
    can_guarantee,
    combined_affordability,
    control_passport,
    control_truecost,
    missing_kyc_docs,
    referencing_readiness,
    required_income_band,
    required_monthly_income,
    true_cost,
)

from nomorals.property.value import (
    DISCLAIMER as VALUE_DISCLAIMER,
    Comp,
    ValueEstimate,
    ValueStore,
    estimate_value,
    pick_comps,
    control_value,
    control_valuepick,
)

__all__ = [
    "AREA_NORMS",
    "ILLEGAL_FEE_TERMS",
    "ScamFlag",
    "ScamReport",
    "ScamStore",
    "check_listing",
    "control_scamcheck",
    "AFFORDABILITY_RATIO",
    "AGENCY_PCT",
    "LEGAL_PCT",
    "INCOME_BANDS",
    "ATTESTATION_VALID_DAYS",
    "NIGERIA_KYC_DOCS",
    "CostBreakdown",
    "DocRef",
    "RentalHistory",
    "RentalPassport",
    "Reference",
    "PassportStore",
    "affordability",
    "can_afford",
    "can_guarantee",
    "combined_affordability",
    "control_passport",
    "control_truecost",
    "missing_kyc_docs",
    "referencing_readiness",
    "required_income_band",
    "required_monthly_income",
    "true_cost",
    "VALUE_DISCLAIMER",
    "Comp",
    "ValueEstimate",
    "ValueStore",
    "estimate_value",
    "pick_comps",
    "control_value",
    "control_valuepick",
]
