"""Property intelligence: rental scam detection, passports, valuations."""

from nomorals.property.scam import (
    AREA_NORMS,
    ILLEGAL_FEE_TERMS,
    ScamFlag,
    ScamReport,
    ScamStore,
    check_listing,
    control_scamcheck,
)
from nomorals.property.passport import (
    AFFORDABILITY_RATIO,
    AGENCY_PCT,
    LEGAL_PCT,
    INCOME_BANDS,
    CostBreakdown,
    DocRef,
    RentalHistory,
    RentalPassport,
    Reference,
    PassportStore,
    affordability,
    can_afford,
    control_passport,
    control_truecost,
    true_cost,
)

__all__ = [
    "AREA_NORMS",
    "ILLEGAL_FEE_TERMS",
    "ScamFlag",
    "ScamReport",
    "ScamStore",
    "check_listing",
    "control_scamcheck",
    "AFFORDABILITY_RATIO",
    "AGENCY_PCT",
    "LEGAL_PCT",
    "INCOME_BANDS",
    "CostBreakdown",
    "DocRef",
    "RentalHistory",
    "RentalPassport",
    "Reference",
    "PassportStore",
    "affordability",
    "can_afford",
    "control_passport",
    "control_truecost",
    "true_cost",
]
