"""Console UI for the Devon chat bot: colors, dashboard, console commands.

The palette deliberately avoids black backgrounds and red text — the owner
hates both. Blues, greens, cyans, purples, whites and yellows only.
"""

from __future__ import annotations

from .avatar import (
    AVATAR_STYLES,
    avatar_size,
    list_avatar_styles,
    render_avatar,
    render_ninja,
    render_ninja_mini,
)
from .banner import BANNER_STYLES, list_banner_styles, render_banner, tip_of_the_day
from .commands import ConsoleCommands, complete
from .dashboard import (
    render_adapters_view,
    render_dashboard,
    render_debug_view,
    render_games_view,
    render_health_view,
    render_llm_view,
    render_scheduler_view,
    render_status_line,
    render_statusbar,
    render_summary,
    render_top_view,
    render_view,
)
from .debug import DebugHub
from .godconsole import EventBuffer, GodConsole, InputLine
from .palette import (
    BOX_DOUBLE,
    BOX_HEAVY,
    BOX_ROUNDED,
    BOX_SINGLE,
    ITALIC,
    REVERSE,
    SEMANTIC,
    STRIKE,
    UNDERLINE,
    hex_color,
    pad_visible,
    paint,
    paint_sem,
    rgb,
    strip_ansi,
    supports_color,
    truncate_visible,
    visible_width,
    wrap_visible,
)
from .themes import (
    ROLES,
    describe_theme,
    get_theme,
    list_themes,
    theme_name,
    theme_preview,
    validate_theme,
)
from .widgets import (
    AVATAR,
    WATCH_VIEW_KEYS,
    WATCH_VIEWS,
    GodScreen,
    LiveScreen,
    MessageEvent,
    MessageFeed,
    ProgressBar,
    Spinner,
    WatchHub,
    barchart,
    braille_chart,
    columns_chart,
    format_feed_line,
    format_message_card,
    gauge,
    gradient_text,
    heatmap,
    panel,
    rule_caption,
    sparkline,
    status,
    table,
)

__all__ = [
    "AVATAR",
    "AVATAR_STYLES",
    "BANNER_STYLES",
    "BOX_DOUBLE",
    "BOX_HEAVY",
    "BOX_ROUNDED",
    "BOX_SINGLE",
    "ITALIC",
    "REVERSE",
    "ROLES",
    "SEMANTIC",
    "STRIKE",
    "UNDERLINE",
    "WATCH_VIEW_KEYS",
    "WATCH_VIEWS",
    "ConsoleCommands",
    "DebugHub",
    "EventBuffer",
    "GodConsole",
    "GodScreen",
    "InputLine",
    "LiveScreen",
    "MessageEvent",
    "MessageFeed",
    "ProgressBar",
    "Spinner",
    "WatchHub",
    "avatar_size",
    "barchart",
    "braille_chart",
    "columns_chart",
    "complete",
    "describe_theme",
    "format_feed_line",
    "format_message_card",
    "gauge",
    "get_theme",
    "gradient_text",
    "heatmap",
    "hex_color",
    "list_avatar_styles",
    "list_banner_styles",
    "list_themes",
    "pad_visible",
    "paint",
    "paint_sem",
    "panel",
    "render_adapters_view",
    "render_avatar",
    "render_banner",
    "render_dashboard",
    "render_debug_view",
    "render_games_view",
    "render_health_view",
    "render_llm_view",
    "render_ninja",
    "render_ninja_mini",
    "render_scheduler_view",
    "render_status_line",
    "render_statusbar",
    "render_summary",
    "render_top_view",
    "render_view",
    "rgb",
    "rule_caption",
    "sparkline",
    "status",
    "strip_ansi",
    "supports_color",
    "table",
    "theme_name",
    "theme_preview",
    "tip_of_the_day",
    "truncate_visible",
    "validate_theme",
    "visible_width",
    "wrap_visible",
]
