"""Custom tool wave50_ping — p (generated by the tool creator, 2026-09-29)."""

from __future__ import annotations
def register(registry):
    @registry.register("wave50_ping", description="p", capability="io", parameters={"n": "str"})
    def wave50_ping(n: str = "hi"):
        return {"ok": True, "greeting": n}
